# Generated by Django 4.1.5 on 2023-01-30 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('register_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Cancelled')], default=1, max_length=15)),
                ('is_active', models.CharField(choices=[('1', 'Yes'), ('2', 'No')], default=1, max_length=17)),
                ('expected_start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('priority', models.CharField(choices=[('1', 'Medium'), ('2', 'Low'), ('3', 'High')], default=1, max_length=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=80)),
                ('status', models.CharField(choices=[('1', 'Open'), ('2', 'Completed'), ('3', 'Cancelled')], default=1, max_length=15)),
                ('type', models.CharField(choices=[('1', 'internal'), ('2', 'external')], default=1, max_length=15)),
                ('expected_start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('priority', models.CharField(choices=[('1', 'Medium'), ('2', 'Low'), ('3', 'High')], default=1, max_length=15)),
                ('description', models.TextField(blank=True)),
                ('assign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.normaluser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management_app.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['project', 'task_name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_management_app.projecttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
