# Generated by Django 4.1.5 on 2023-01-31 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NormalUser',
        ),
    ]
