# Generated by Django 4.1.5 on 2023-02-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(upload_to='profile'),
        ),
    ]
