# Generated by Django 4.1.5 on 2023-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0008_alter_userprofile_img_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='blank_profile', null=True, upload_to=''),
        ),
    ]
