# Generated by Django 4.1.5 on 2023-02-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0009_alter_userprofile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, default='blank_profile.png', null=True, upload_to=''),
        ),
    ]
