# Generated by Django 4.1.5 on 2023-02-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_management_app', '0002_rename_user_project_assign_remove_projecttype_user_and_more'),
        ('register_app', '0010_alter_userprofile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.company'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='project_management_app.project'),
        ),
    ]
