# Generated by Django 4.1.5 on 2023-02-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0012_alter_userprofile_company_alter_userprofile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='project',
        ),
    ]
